volumes:
    langgraph-data:
        driver: local
    chroma-db-storage:  # Persistent storage for ChromaDB
        driver: local

services:
    langgraph-redis:
        image: redis:6
        healthcheck:
            test: redis-cli ping
            interval: 5s
            timeout: 1s
            retries: 5

    langgraph-postgres:
        image: postgres:16
        ports:
            - "5433:5432"
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - langgraph-data:/var/lib/postgresql/data
        healthcheck:
            test: pg_isready -U postgres
            start_period: 10s
            timeout: 1s
            retries: 5
            interval: 5s

    langgraph-api:
        # build:
        #     context: .
        #     dockerfile: Dockerfile
        # image: langchain/langgraph-api:3.11
        image: linkfusionaiagent:latest
        container_name: langgraph-api
        ports:
            - "8123:8000"
        depends_on:
            langgraph-redis:
                condition: service_healthy
            langgraph-postgres:
                condition: service_healthy
        env_file:
            - .env
        environment:
            REDIS_URI: redis://langgraph-redis:6379
            LANGSMITH_API_KEY: ${LANGSMITH_API_KEY}
            POSTGRES_URI: postgres://postgres:postgres@langgraph-postgres:5432/postgres?sslmode=disable
        volumes:
            - ./data/vector_db:/app/data/vector_db  # Mount ChromaDB persistent storage
    
    # fastapi-chat:
    #     build:
    #         context: .
    #         network: host
    #     container_name: fastapi-chat
    #     ports:
    #         - "4000:8000"
    #     depends_on:
    #         langgraph-redis:
    #             condition: service_healthy
    #         langgraph-postgres:
    #             condition: service_healthy
    #         langgraph-api:
    #             condition: service_healthy

# networks:
#     chatnet:
#         driver: bridge
#         ipam:
#             config:
#                 - subnet: 192.168.1.0/24 